services:
  tater-tube-server:
    image: ghcr.io/tatertotterson/tater-tube-server:latest
    container_name: tater-tube-server
    volumes:
      - ./config:/config
    ports:
      - "8080:8080"
    restart: unless-stopped
