package api

import (
	"context"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/TaterTotterson/tater-tube-server/internal/config"
	"github.com/gofiber/fiber/v2"
)

func TestTaterTVAutoLogoFileMatchesThemedAndBaseChannels(t *testing.T) {
	tests := []struct {
		source taterTVSource
		want   string
	}{
		{source: taterTVSource{Title: "ACTION MOVIES"}, want: "action-movies.png"},
		{source: taterTVSource{Title: "My Library SCI-FI CHANNEL"}, want: "sci-fi-channel.png"},
		{source: taterTVSource{Title: "90S MOVIES"}, want: "90s-movies.png"},
		{source: taterTVSource{Title: "Shows", Groups: []taterTVEpisodeGroup{{Title: "One"}}}, want: "tv.png"},
		{source: taterTVSource{Title: "Cinema", Programs: []taterUsenetItem{{Title: "One"}}}, want: "movies.png"},
	}
	for _, test := range tests {
		if got := taterTVAutoLogoFile(test.source); got != test.want {
			t.Fatalf("taterTVAutoLogoFile(%q) = %q, want %q", test.source.Title, got, test.want)
		}
	}
}

func TestTaterTVAutoLogoCatalogAssetsAreEmbedded(t *testing.T) {
	files := []string{"movies.png", "tv.png"}
	for _, logo := range taterTVAutoLogoNames {
		files = append(files, logo.File)
	}
	for _, file := range files {
		data, err := taterTVAutoLogoAssets.ReadFile("assets/tube-tv-auto-logos/" + file)
		if err != nil {
			t.Fatalf("auto channel logo %q is not embedded: %v", file, err)
		}
		if len(data) < 8 || string(data[:8]) != "\x89PNG\r\n\x1a\n" {
			t.Fatalf("auto channel logo %q is not a PNG", file)
		}
	}
}

func TestTaterTVApplyAndResolveEmbeddedAutoLogo(t *testing.T) {
	cfg := config.DefaultConfig(t.TempDir())
	cfg.Metadata.RootPath = filepath.Join(t.TempDir(), "metadata")
	cfg.TubeTV.AutoChannelLogoPosition = "top_left"
	source := taterTVSource{Title: "ACTION MOVIES"}

	taterTVApplyAutoChannelLogo(cfg, &source)
	if source.LogoPath != "tater-auto/action-movies.png" || !source.AutoGenerated {
		t.Fatalf("auto logo was not applied: %#v", source)
	}
	if source.LogoPosition != "top_left" {
		t.Fatalf("auto logo position = %q", source.LogoPosition)
	}

	logoFile, err := taterTVResolveLogoFile(context.Background(), cfg, source.LogoPath)
	if err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(logoFile)
	if err != nil {
		t.Fatal(err)
	}
	if len(data) < 8 || string(data[:8]) != "\x89PNG\r\n\x1a\n" {
		t.Fatalf("resolved file is not a PNG: %q", logoFile)
	}
	if !strings.Contains(logoFile, filepath.Join("tube-tv-channel-logos", "tater-auto")) {
		t.Fatalf("embedded logo was cached outside the channel logo root: %q", logoFile)
	}
}

func TestTaterTVAutoLogoPlaybackSettingIsIndependent(t *testing.T) {
	cfg := config.DefaultConfig(t.TempDir())
	disabled := false
	cfg.TubeTV.AutoChannelLogoOverlayEnabled = &disabled

	if taterTVChannelLogoEnabled(cfg, taterTVChannel{AutoGenerated: true}) {
		t.Fatal("auto channel overlay should be disabled")
	}
	if !taterTVChannelLogoEnabled(cfg, taterTVChannel{}) {
		t.Fatal("custom channel overlay setting should remain enabled")
	}
}

func TestTaterTVChannelLogoAcceptsPlayerTokenFromImageURL(t *testing.T) {
	cfg := config.DefaultConfig(t.TempDir())
	cfg.Players.Paired = []config.PlayerConfig{{
		ID:        "guide-player",
		TokenHash: hashTaterSecret("guide-token"),
	}}
	server := &Server{configManager: &mockConfigManager{cfg: cfg}}
	app := fiber.New()
	app.Get("/api/v1/player/artwork/channel-logo", server.handleTaterTVChannelLogo)

	request := httptest.NewRequest(http.MethodGet,
		"/api/v1/player/artwork/channel-logo?player_token=guide-token", nil)
	response, err := app.Test(request)
	if err != nil {
		t.Fatal(err)
	}
	if response.StatusCode != http.StatusBadRequest {
		t.Fatalf("authenticated image request status = %d, want %d", response.StatusCode, http.StatusBadRequest)
	}
}
